create extension if not exists pgcrypto;
create table if not exists public.task_sop_library (
  id uuid primary key default gen_random_uuid(),
  record_type text not null check (record_type in ('task','sop')),
  task_id text,
  sop_id text,
  title text,
  system_family text,
  vendor_flavor text,
  phase text,
  service_tiers jsonb,
  frequency text,
  estimated_duration_min int,
  audience_level int,
  initial_steps text,
  sop_refs jsonb,
  acceptance_criteria text,
  artifacts text,
  prerequisites text,
  tools_required text,
  safety_tags text,
  reference_links text,
  notes text,
  owner text,
  last_updated timestamptz,
  version text,
  goal text,
  ui_navigation text,
  step_list_core text,
  step_list_assure text,
  step_list_guardian text,
  verification_steps text,
  rollback_steps text,
  best_practices text,
  is_active boolean default true,
  created_at timestamptz default now()
);
