-- Insert missing task categories for SOPs
INSERT INTO ame_task_categories (category_name, description, color, is_essential) VALUES
('Documentation', 'Documentation and record keeping tasks', '#6366f1', true),
('Operations', 'Operational support and training tasks', '#10b981', true),
('IT & Infrastructure', 'IT infrastructure and server maintenance tasks', '#f59e0b', true)
ON CONFLICT (category_name) DO NOTHING;

-- Import remaining SOPs (8-13) with rich content parsing
INSERT INTO ame_sops_normalized (
  sop_id,
  title,
  category,
  goal,
  original_steps_html,
  rich_content,
  steps,
  best_practices,
  tools_required,
  hyperlinks,
  estimated_duration_minutes,
  created_at,
  last_updated
) VALUES
-- SOP 8: Alarm & Analytics Review
('8', 'Alarm & Analytics Review', 'System Maintenance',
 'Review active and historical alarms and analytics to ensure critical issues are addressed, reduce nuisance alarms, and verify that fault detection logic is effective.',
 ' Active Alarm Console Review: Open the Alarm Console and sort by priority. Address all CRITICAL alarms first by investigating the source, taking corrective action, and acknowledging the alarm. Repeat for high and medium priority alarms.<br> Analyze Alarm History: Switch to the history view to identify recurring alarms. Frequent, repetitive alarms often point to underlying equipment issues or poorly configured alarm limits that need to be fixed.<br> Review Alarm Settings: Check Alarm Class configurations to ensure notifications (email, SMS) are routing to the correct, up-to-date recipient lists. Test alarm delivery if possible.<br> Review Analytics/Fault Detection: If an analytics package is installed, review its findings for any detected faults (e.g., simultaneous heating and cooling). Validate that the findings are true and tune the analytic rules or thresholds as needed.<br> Document & Clear: Summarize findings, document recommendations for preventive action, and acknowledge all alarms to clear the active console. This provides a clean slate for new alarms.',
 ' Active Alarm Console Review: Open the Alarm Console and sort by priority. Address all CRITICAL alarms first by investigating the source, taking corrective action, and acknowledging the alarm. Repeat for high and medium priority alarms.<br> Analyze Alarm History: Switch to the history view to identify recurring alarms. Frequent, repetitive alarms often point to underlying equipment issues or poorly configured alarm limits that need to be fixed.<br> Review Alarm Settings: Check Alarm Class configurations to ensure notifications (email, SMS) are routing to the correct, up-to-date recipient lists. Test alarm delivery if possible.<br> Review Analytics/Fault Detection: If an analytics package is installed, review its findings for any detected faults (e.g., simultaneous heating and cooling). Validate that the findings are true and tune the analytic rules or thresholds as needed.<br> Document & Clear: Summarize findings, document recommendations for preventive action, and acknowledge all alarms to clear the active console. This provides a clean slate for new alarms.',
 '[{"step_number": 1, "content": "Active Alarm Console Review: Open the Alarm Console and sort by priority. Address all CRITICAL alarms first by investigating the source, taking corrective action, and acknowledging the alarm. Repeat for high and medium priority alarms.\n Analyze Alarm History: Switch to the history view to identify recurring alarms. Frequent, repetitive alarms often point to underlying equipment issues or poorly configured alarm limits that need to be fixed.\n Review Alarm Settings: Check Alarm Class configurations to ensure notifications (email, SMS) are routing to the correct, up-to-date recipient lists. Test alarm delivery if possible.\n Review Analytics/Fault Detection: If an analytics package is installed, review its findings for any detected faults (e.g., simultaneous heating and cooling). Validate that the findings are true and tune the analytic rules or thresholds as needed.\n Document & Clear: Summarize findings, document recommendations for preventive action, and acknowledge all alarms to clear the active console. This provides a clean slate for new alarms.", "references": []}]',
 ' Work with facility staff to establish an "alarm philosophy" that defines what is truly alarm-worthy, focusing on actionable events.<br> Use Niagaras alarm classes consistently to categorize and prioritize alarms effectively.<br> Hold regular (e.g., monthly) meetings to review alarm logs and discuss root causes of recurring issues.<br> Keep a log or knowledge base documenting how complex alarms were resolved for future reference.<br> Ensure analytics rules are maintained and updated as building equipment or usage changes.',
 '["TOOL_041", "TOOL_029"]',
 '[]',
 45, now(), now()),

-- SOP 9: Field Device & Actuator Testing
('9', 'Field Device & Actuator Testing', 'System Maintenance',
 'Physically test field devices and actuators (valves, dampers, etc.) to ensure they respond correctly to control signals from Niagara, catching mechanical issues before they lead to system failure.',
 ' Plan the Testing: Prioritize critical and problematic devices. Coordinate with on-site staff to minimize disruption. <br>  Override Outputs via Niagara: Use Workbench to override the actuator''s control point to test its range of motion (e.g., 0%, 50%, 100%) [1]. Verify that any available feedback matches the command. <br>  Physical Verification: In the field, observe the device to confirm it moves smoothly and fully [2]. Check linkages for tightness [3] and listen for unusual noises [4, 5]. For fail-safe devices, test the spring-return function [6]. <br>  Test Manual Override: If available, test the manual override lever and ensure it is disengaged afterward [7]. <br>  Return to Auto: Crucially, release all overrides in Niagara so the system returns to automatic control. <br>  Document Findings: Note any device that failed or performed sub-optimally and recommend a resolution.',
 ' Plan the Testing: Prioritize critical and problematic devices. Coordinate with on-site staff to minimize disruption. <br>  Override Outputs via Niagara: Use Workbench to override the actuator''s control point to test its range of motion (e.g., 0%, 50%, 100%) [1]. Verify that any available feedback matches the command. <br>  Physical Verification: In the field, observe the device to confirm it moves smoothly and fully [2]. Check linkages for tightness [3] and listen for unusual noises [4, 5]. For fail-safe devices, test the spring-return function [6]. <br>  Test Manual Override: If available, test the manual override lever and ensure it is disengaged afterward [7]. <br>  Return to Auto: Crucially, release all overrides in Niagara so the system returns to automatic control. <br>  Document Findings: Note any device that failed or performed sub-optimally and recommend a resolution.',
 '[{"step_number": 1, "content": "Plan the Testing: Prioritize critical and problematic devices. Coordinate with on-site staff to minimize disruption. \n  Override Outputs via Niagara: Use Workbench to override the actuator''s control point to test its range of motion (e.g., 0%, 50%, 100%) [1]. Verify that any available feedback matches the command. \n  Physical Verification: In the field, observe the device to confirm it moves smoothly and fully [2]. Check linkages for tightness [3] and listen for unusual noises [4, 5]. For fail-safe devices, test the spring-return function [6]. \n  Test Manual Override: If available, test the manual override lever and ensure it is disengaged afterward [7]. \n  Return to Auto: Crucially, release all overrides in Niagara so the system returns to automatic control. \n  Document Findings: Note any device that failed or performed sub-optimally and recommend a resolution.", "references": [1, 2, 3, 4, 5, 6, 7]}]',
 ' Exercise actuators regularly (at least annually) to prevent them from seizing. <br>  Use a standardized checklist to ensure all mechanical aspects are inspected [8, 9]. <br>  Calibrate actuators that have adjustable stops or feedback so their physical position accurately matches the signal from Niagara. <br>  Take safety precautions and be mindful of the operational impact of your overrides. <br>  Use a team approach (one person at the workstation, one in the field) to speed up testing.',
 '["TOOL_041", "TOOL_029", "TOOL_013"]',
 '[{"ref_number": 1, "url": "https://www.getmaintainx.com/procedures/d/ZNytKP1vSts/checklist-for-valve-and-damper-actuator-inspection", "title": "Valve and Damper Actuator Inspection", "display_text": "Reference 1"}, {"ref_number": 2, "url": "https://www.getmaintainx.com/procedures/d/ZNytKP1vSts/checklist-for-valve-and-damper-actuator-inspection", "title": "Valve and Damper Actuator Inspection", "display_text": "Reference 2"}, {"ref_number": 3, "url": "https://www.getmaintainx.com/procedures/d/ZNytKP1vSts/checklist-for-valve-and-damper-actuator-inspection", "title": "Valve and Damper Actuator Inspection", "display_text": "Reference 3"}, {"ref_number": 4, "url": "https://www.getmaintainx.com/procedures/d/ZNytKP1vSts/checklist-for-valve-and-damper-actuator-inspection", "title": "Valve and Damper Actuator Inspection", "display_text": "Reference 4"}, {"ref_number": 5, "url": "https://www.getmaintainx.com/procedures/d/ZNytKP1vSts/checklist-for-valve-and-damper-actuator-inspection", "title": "Valve and Damper Actuator Inspection", "display_text": "Reference 5"}, {"ref_number": 6, "url": "https://www.getmaintainx.com/procedures/d/ZNytKP1vSts/checklist-for-valve-and-damper-actuator-inspection", "title": "Valve and Damper Actuator Inspection", "display_text": "Reference 6"}, {"ref_number": 7, "url": "https://www.getmaintainx.com/procedures/d/ZNytKP1vSts/checklist-for-valve-and-damper-actuator-inspection", "title": "Valve and Damper Actuator Inspection", "display_text": "Reference 7"}]',
 45, now(), now()),

-- SOP 10: Documentation & Reporting
('10', 'Documentation & Reporting', 'Documentation',
 'Update all relevant documentation and provide a clear maintenance report detailing the work performed, findings, and recommendations to preserve knowledge and inform stakeholders.',
 ' Update Drawings & Schematics: "Redline" any control drawings with changes made to logic, setpoints, or hardware. This information must eventually be transferred to the official as-built documents [1]. <br>  Update Points List: If points were added or removed, update the master points list. <br>  Create Maintenance Log: Enter a brief summary of the visit and actions taken into a station log file within Niagara. <br>  Generate Service Report: Prepare a formal report for the client detailing tasks performed, issues found, corrective actions taken, and recommendations for next steps. <br>  Review and Sign-off: Briefly review the report with the client to ensure they understand the findings and get their sign-off. <br>  Organize & Archive: Save all updated documents (report, backup, redlines) to a centralized, organized repository.',
 ' Update Drawings & Schematics: "Redline" any control drawings with changes made to logic, setpoints, or hardware. This information must eventually be transferred to the official as-built documents [1]. <br>  Update Points List: If points were added or removed, update the master points list. <br>  Create Maintenance Log: Enter a brief summary of the visit and actions taken into a station log file within Niagara. <br>  Generate Service Report: Prepare a formal report for the client detailing tasks performed, issues found, corrective actions taken, and recommendations for next steps. <br>  Review and Sign-off: Briefly review the report with the client to ensure they understand the findings and get their sign-off. <br>  Organize & Archive: Save all updated documents (report, backup, redlines) to a centralized, organized repository.',
 '[{"step_number": 1, "content": "Update Drawings & Schematics: \"Redline\" any control drawings with changes made to logic, setpoints, or hardware. This information must eventually be transferred to the official as-built documents [1]. \n  Update Points List: If points were added or removed, update the master points list. \n  Create Maintenance Log: Enter a brief summary of the visit and actions taken into a station log file within Niagara. \n  Generate Service Report: Prepare a formal report for the client detailing tasks performed, issues found, corrective actions taken, and recommendations for next steps. \n  Review and Sign-off: Briefly review the report with the client to ensure they understand the findings and get their sign-off. \n  Organize & Archive: Save all updated documents (report, backup, redlines) to a centralized, organized repository.", "references": [1]}]',
 ' Standardize reports using a consistent template for all sites. <br>  Use checklists and tables to clearly show which tasks were completed. <br>  Record key data like critical setpoints as a historical snapshot. <br>  Maintain a central document repository with a clear folder structure and version control. <br>  Establish a reliable process for transferring field redlines to the official as-built drawings [2].',
 '["TOOL_041", "TOOL_029", "TOOL_035"]',
 '[{"ref_number": 1, "url": "https://fm.unm.edu/assets/documents/utilities%20pdfs/A%2006%20UNM%20Utilities%20Guidelines%20for%20Construction_1.pdf", "title": "UNM Utilities Guidelines", "display_text": "Reference 1"}, {"ref_number": 2, "url": "https://fm.unm.edu/assets/documents/utilities%20pdfs/A%2006%20UNM%20Utilities%20Guidelines%20for%20Construction_1.pdf", "title": "UNM Utilities Guidelines", "display_text": "Reference 2"}]',
 45, now(), now()),

-- SOP 11: Training & Customer Support
('11', 'Training & Customer Support', 'Operations',
 'Provide training and support to end-users so they can effectively operate the Niagara BAS, handle minor issues, and know how to get help when needed.',
 ' Operator Training/Refreshers: During maintenance visits, review the BAS interface, alarm management, and how to adjust schedules and setpoints.<br> Provide Documentation/Guides: Create and distribute user-friendly, quick-reference guides with screenshots for common tasks.<br> Interactive Q&A: Encourage staff to ask questions and use their feedback to address pain points, which may involve system adjustments.<br> Highlight Best Practices: Teach users simple best practices, like avoiding permanent overrides and performing proper system shutdowns.<br> Establish Support Avenues: Ensure the customer has clear contact information for routine and emergency support.<br> Train New Users: When staff turnover occurs, recommend a formal training session or an official Niagara operator course [1, 2].',
 ' Operator Training/Refreshers: During maintenance visits, review the BAS interface, alarm management, and how to adjust schedules and setpoints.<br> Provide Documentation/Guides: Create and distribute user-friendly, quick-reference guides with screenshots for common tasks.<br> Interactive Q&A: Encourage staff to ask questions and use their feedback to address pain points, which may involve system adjustments.<br> Highlight Best Practices: Teach users simple best practices, like avoiding permanent overrides and performing proper system shutdowns.<br> Establish Support Avenues: Ensure the customer has clear contact information for routine and emergency support.<br> Train New Users: When staff turnover occurs, recommend a formal training session or an official Niagara operator course [1, 2].',
 '[{"step_number": 1, "content": "Operator Training/Refreshers: During maintenance visits, review the BAS interface, alarm management, and how to adjust schedules and setpoints.\n Provide Documentation/Guides: Create and distribute user-friendly, quick-reference guides with screenshots for common tasks.\n Interactive Q&A: Encourage staff to ask questions and use their feedback to address pain points, which may involve system adjustments.\n Highlight Best Practices: Teach users simple best practices, like avoiding permanent overrides and performing proper system shutdowns.\n Establish Support Avenues: Ensure the customer has clear contact information for routine and emergency support.\n Train New Users: When staff turnover occurs, recommend a formal training session or an official Niagara operator course [1, 2].", "references": [1, 2]}]',
 ' Customize training to the technical level of the audience, using simple language and visual aids.<br> Encourage continuous education with periodic refresher sessions.<br> Document all training provided in the service report.<br> Create a feedback loop by following up after training to see if users have further questions or if the system UI can be simplified.',
 '["TOOL_041", "TOOL_029"]',
 '[{"ref_number": 1, "url": "https://www.niagaramarketplace.com/niagara-4-operator-end-user-training.html", "title": "Niagara 4 Operator Training", "display_text": "Reference 1"}, {"ref_number": 2, "url": "https://www.tridiumuniversity.com/student/page/961603-n4-op-end-amer", "title": "Tridium University Training", "display_text": "Reference 2"}]',
 45, now(), now()),

-- SOP 12: Server Maintenance
('12', 'Server Maintenance', 'IT & Infrastructure',
 'Maintain the underlying host system (OS, hardware, network settings) for a Niagara Supervisor to ensure reliability, security, and performance.',
 ' Operating System Updates: Periodically apply OS security patches after hours, ensuring Niagara services are shut down gracefully first.<br> Monitor Hardware Resources: Check server CPU and RAM usage to ensure Niagara and other processes are not causing bottlenecks. A CPU utilization below ~80% is a common guideline [1, 2].<br> Manage Disk and File System: Ensure the server has adequate free disk space (>20%). Archive old backups and logs, and perform disk cleanup as needed.<br> Verify Niagara Service Health: Check that the Niagara service is set to auto-start on boot and that recovery options are configured to restart it automatically if it fails.<br> Review Firewall Settings: Ensure firewall rules correctly allow inbound traffic for all necessary Niagara ports (e.g., 4911, 5011, 443) [3, 4] and that these rules are appropriately scoped.<br> Backup the Server: In addition to the Niagara station backup, ensure the entire server/VM is backed up regularly.',
 ' Operating System Updates: Periodically apply OS security patches after hours, ensuring Niagara services are shut down gracefully first.<br> Monitor Hardware Resources: Check server CPU and RAM usage to ensure Niagara and other processes are not causing bottlenecks. A CPU utilization below ~80% is a common guideline [1, 2].<br> Manage Disk and File System: Ensure the server has adequate free disk space (>20%). Archive old backups and logs, and perform disk cleanup as needed.<br> Verify Niagara Service Health: Check that the Niagara service is set to auto-start on boot and that recovery options are configured to restart it automatically if it fails.<br> Review Firewall Settings: Ensure firewall rules correctly allow inbound traffic for all necessary Niagara ports (e.g., 4911, 5011, 443) [3, 4] and that these rules are appropriately scoped.<br> Backup the Server: In addition to the Niagara station backup, ensure the entire server/VM is backed up regularly.',
 '[{"step_number": 1, "content": "Operating System Updates: Periodically apply OS security patches after hours, ensuring Niagara services are shut down gracefully first.\n Monitor Hardware Resources: Check server CPU and RAM usage to ensure Niagara and other processes are not causing bottlenecks. A CPU utilization below ~80% is a common guideline [1, 2].\n Manage Disk and File System: Ensure the server has adequate free disk space (>20%). Archive old backups and logs, and perform disk cleanup as needed.\n Verify Niagara Service Health: Check that the Niagara service is set to auto-start on boot and that recovery options are configured to restart it automatically if it fails.\n Review Firewall Settings: Ensure firewall rules correctly allow inbound traffic for all necessary Niagara ports (e.g., 4911, 5011, 443) [3, 4] and that these rules are appropriately scoped.\n Backup the Server: In addition to the Niagara station backup, ensure the entire server/VM is backed up regularly.", "references": [1, 2, 3, 4]}]',
 ' Establish a regular maintenance window for server updates and reboots, coordinating with the client''s IT department.<br> Use monitoring tools to proactively track server health (CPU, memory, disk space).<br> Follow OS hardening guidelines by disabling unnecessary services and using strong account passwords.<br> Document the server configuration, including OS version, IP settings, and Niagara details.<br> Test fail-safes by occasionally taking the Supervisor offline to ensure JACEs and field controllers operate robustly on their own.',
 '["TOOL_041", "TOOL_029", "TOOL_057"]',
 '[{"ref_number": 1, "url": "https://support.onesight.solutions/kb/faq.php?id=46", "title": "OneSight Support", "display_text": "Reference 1"}, {"ref_number": 2, "url": "https://know.innon.com/run-basic-diagnostics-on-jace", "title": "JACE Diagnostics", "display_text": "Reference 2"}, {"ref_number": 3, "url": "https://know.innon.com/im-having-trouble-getting-my-niagara-network-up-and-running", "title": "Niagara Network Setup", "display_text": "Reference 3"}, {"ref_number": 4, "url": "https://know.innon.com/im-having-trouble-getting-my-niagara-network-up-and-running", "title": "Niagara Network Setup", "display_text": "Reference 4"}]',
 45, now(), now()),

-- SOP 13: BAS Documentation Management
('13', 'BAS Documentation Management', 'Documentation',
 'Maintain an organized, up-to-date set of all BAS documentation to ensure the system can be effectively understood, troubleshot, and upgraded.',
 ' Organize Document Repositories: Establish a central digital location for all control drawings, points lists, sequences of operation, network diagrams, and program documentation.<br> Manage Redlines and As-Builts: Implement a process where field changes are marked up ("redlined") and then periodically incorporated into the official "as-built" master documents [1]. Use version control with dates or revision numbers.<br> Maintain Vendor Documentation: Collect and store electronic copies of all product manuals, datasheets, and programming guides for installed controllers, sensors, and actuators.<br> Document Control Programs: Use comments and annotations within Niagara wire sheets to explain complex logic.<br> Label Devices in the Field: Ensure physical device labels match the names and IDs used in the documentation.',
 ' Organize Document Repositories: Establish a central digital location for all control drawings, points lists, sequences of operation, network diagrams, and program documentation.<br> Manage Redlines and As-Builts: Implement a process where field changes are marked up ("redlined") and then periodically incorporated into the official "as-built" master documents [1]. Use version control with dates or revision numbers.<br> Maintain Vendor Documentation: Collect and store electronic copies of all product manuals, datasheets, and programming guides for installed controllers, sensors, and actuators.<br> Document Control Programs: Use comments and annotations within Niagara wire sheets to explain complex logic.<br> Label Devices in the Field: Ensure physical device labels match the names and IDs used in the documentation.',
 '[{"step_number": 1, "content": "Organize Document Repositories: Establish a central digital location for all control drawings, points lists, sequences of operation, network diagrams, and program documentation.\n Manage Redlines and As-Builts: Implement a process where field changes are marked up (\"redlined\") and then periodically incorporated into the official \"as-built\" master documents [1]. Use version control with dates or revision numbers.\n Maintain Vendor Documentation: Collect and store electronic copies of all product manuals, datasheets, and programming guides for installed controllers, sensors, and actuators.\n Document Control Programs: Use comments and annotations within Niagara wire sheets to explain complex logic.\n Label Devices in the Field: Ensure physical device labels match the names and IDs used in the documentation.", "references": [1]}]',
 ' Adhere to documentation standards for drawings, symbols, and point naming conventions.<br> Keep a change log to document the history of system modifications.<br> Periodically audit the documentation by comparing it against the actual system to ensure it hasn''t drifted from reality.<br> Ensure documentation is backed up and accessible to those who need it.<br> Put a QR code on major equipment that links to its documentation for quick field access.',
 '["TOOL_041", "TOOL_029", "TOOL_035"]',
 '[{"ref_number": 1, "url": "https://fm.unm.edu/assets/documents/utilities%20pdfs/A%2006%20UNM%20Utilities%20Guidelines%20for%20Construction_1.pdf", "title": "UNM Utilities Guidelines", "display_text": "Reference 1"}]',
 45, now(), now())

ON CONFLICT (sop_id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  goal = EXCLUDED.goal,
  original_steps_html = EXCLUDED.original_steps_html,
  rich_content = EXCLUDED.rich_content,
  steps = EXCLUDED.steps,
  best_practices = EXCLUDED.best_practices,
  tools_required = EXCLUDED.tools_required,
  hyperlinks = EXCLUDED.hyperlinks,
  last_updated = now();